- name: testing command module
  hosts: testserver01
  become: true

  tasks:
    - name: Get hostname using command module
      command: hostname
      register: result

    - name: Display the result
      debug:
        var: result

    - name: multiple commands
      command: df -h
      register: multiple_commands_result

    - name: Display the result of multiple commands
      debug:
        var: multiple_commands_result

    - name: display stdout lines
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ result.stdout_lines }}"
        - "{{ multiple_commands_result.stdout_lines }}"