---
- name: Install Redis Server
  hosts: testserver01
  become: true

  tasks:
    - name: Install Redis dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - tcl
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '24.04'

    - name: Check Redis Status
      shell: systemctl status redis --no-pager
      register: redis_status
      ignore_errors: true

    - name: check register info
      debug:
        msg: "{{ item }}"
      with_items:
       - "{{ redis_status.rc }}"
       - "{{ redis_status.stderr }}"

       
    # - name: check register info
    #   debug:
    #     var: item
    #   with_items:
    #     - "redis_status.rc"
    #     - "redis_status.stderr"
